zingstreamp3_dbt:
  outputs:

    dev:
      dbname: zingstreamp3
      host: postgres_zingstreamp3
      password: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres

    prod:
      dbname: zingstreamp3
      host: postgres_zingstreamp3
      password: postgres
      port: 5432
      schema: staging
      threads: 1
      type: postgres
      user: postgres

  target: prod
