CREATE TABLE IF NOT EXISTS staging.page_view_events (
    ts TIMESTAMP,
    sessionId INTEGER,
    page VARCHAR(255),
    auth VARCHAR(255),
    method VARCHAR(255),
    status INTEGER,
    level VARCHAR(255),
    itemInSession INTEGER,
    city VARCHAR(255),
    zip INTEGER,
    state VARCHAR(255),
    userAgent VARCHAR(255),
    lon DOUBLE PRECISION,
    lat DOUBLE PRECISION,
    userId INTEGER,
    lastName VARCHAR(255),
    firstName VARCHAR(255),
    gender VARCHAR(255),
    registration BIGINT,
    artist VARCHAR(255),
    song VARCHAR(255),
    duration DOUBLE PRECISION,
    month INTEGER,
    day INTEGER,
    hour INTEGER
);